version: '3.3'

services:
  
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-container
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    environment:
      - QDRANT_API_KEY=api-key-123
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

   